Feature engineering

In [3]:
import pandas as pd
import numpy as np

games = pd.read_csv(
    "nba_clean_full.csv",
    parse_dates=["gameDateTimeEst"]
)

games = games.sort_values(
    "gameDateTimeEst"
).reset_index(drop=True)  # reloading the dataset.

Creating team dataset.

In [7]:
home = games[[
    "gameId",
    "gameDateTimeEst",
    "season_year",
    "home_team",
    "away_team",
    "homeScore",
    "awayScore",
    "home_win",
    "is_playoff"
]].copy()

home = home.rename(columns={
    "home_team": "team",
    "away_team": "opponent",
    "homeScore": "points_for",
    "awayScore": "points_against"
})

home["is_home"] = 1

home["win"] = home["home_win"]
home.head()

,gameId,gameDateTimeEst,season_year,team,opponent,points_for,points_against,home_win,is_playoff,is_home,win
0,22000071,2021-01-01 19:00:00,2021,Dallas Mavericks,Miami Heat,93,83,1,0,1,1
1,22000070,2021-01-01 19:00:00,2021,Detroit Pistons,Boston Celtics,96,93,1,0,1,1
2,22000069,2021-01-01 19:00:00,2021,Charlotte Hornets,Memphis Grizzlies,93,108,0,0,1,0
3,22000072,2021-01-01 19:30:00,2021,Brooklyn Nets,Atlanta Hawks,96,114,0,0,1,0
4,22000074,2021-01-01 20:00:00,2021,Minnesota Timberwolves,Washington Wizards,109,130,0,0,1,0

In [ ]:
away = games[[
    "gameId",
    "gameDateTimeEst",
    "season_year",
    "home_team",
    "away_team",
    "homeScore",
    "awayScore",
    "home_win",
    "is_playoff"
]].copy()

away = away.rename(columns={
    "away_team": "team",
    "home_team": "opponent",
    "awayScore": "points_for",
    "homeScore": "points_against"
})

away["is_home"] = 0

away["win"] = 1 - away["home_win"]
away.head()

,gameId,gameDateTimeEst,season_year,opponent,team,points_against,points_for,home_win,is_playoff,is_home,win
0,22000071,2021-01-01 19:00:00,2021,Dallas Mavericks,Miami Heat,93,83,1,0,0,0
1,22000070,2021-01-01 19:00:00,2021,Detroit Pistons,Boston Celtics,96,93,1,0,0,0
2,22000069,2021-01-01 19:00:00,2021,Charlotte Hornets,Memphis Grizzlies,93,108,0,0,0,1
3,22000072,2021-01-01 19:30:00,2021,Brooklyn Nets,Atlanta Hawks,96,114,0,0,0,1
4,22000074,2021-01-01 20:00:00,2021,Minnesota Timberwolves,Washington Wizards,109,130,0,0,0,1

:

Here, when we look at them, the home team and the away team's "Team" iD is changed.

Combining both

In [9]:
team_games = pd.concat(
    [home, away],
    ignore_index=True
)

team_games = team_games.sort_values(
    ["team", "gameDateTimeEst"]
).reset_index(drop=True)
team_games.head()

,gameId,gameDateTimeEst,season_year,team,opponent,points_for,points_against,home_win,is_playoff,is_home,win
0,22000072,2021-01-01 19:30:00,2021,Atlanta Hawks,Brooklyn Nets,114,96,0,0,0,1
1,22000083,2021-01-02 19:30:00,2021,Atlanta Hawks,Cleveland Cavaliers,91,96,0,0,1,0
2,22000095,2021-01-04 19:30:00,2021,Atlanta Hawks,New York Knicks,108,113,0,0,1,0
3,22000110,2021-01-06 19:30:00,2021,Atlanta Hawks,Charlotte Hornets,94,102,0,0,1,0
4,22000134,2021-01-09 19:00:00,2021,Atlanta Hawks,Charlotte Hornets,105,113,1,0,0,0

Creating different points